export const Category = [
    {
        id:1,
        name:'Bestsellers',
        items: 
        [
            {
                id:1,
                img:'https://images.dominos.co.in/new_margherita_2502.jpg',
                itemName:'Margherita',
                itemDesc:'Classic delight with 100% real mozzarella cheese',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'199',         
            },
            {
                id:2,
                img:'https://images.dominos.co.in/farmhouse.png',
                itemName:'Farmhouse',
                itemDesc:'Delightful combination of onion, capsicum, tomato & grilled mushroom',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'395',
            },
            {
                id:3,
                img:'https://images.dominos.co.in/new_peppy_paneer.jpg',
                itemName:'Peppy Paneer',
                itemDesc:'Flavorful trio of juicy paneer, crisp capsicum with spicy red paprika',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false, 
                qty:0,
                price:'395',
            },
            {
                id:4,
                img:'https://images.dominos.co.in/new_veg_extravaganza.jpg',
                itemName:'Veg Extravaganza',
                itemDesc:'Black olives, capsicum, onion, grilled mushroom, corn, tomato, jalapeno & extra cheese',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'450',
            },
            {
                id:5,
                img:'https://images.dominos.co.in/new_veggie_paradise.jpg',
                itemName:'Veggie Paradise',
                itemDesc:'The awesome foursome! Golden corn, black olives, capsicum, red paprika',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'395',
            }
        ],
    },
    {
        id:2,
        name:'Veg pizza',
        items:
        [
            {
                id:1,
                img:'https://images.dominos.co.in/new_veggie_paradise.jpg',
                itemName:'Veggie Paradise',
                itemDesc:'The awesome foursome! Golden corn, black olives, capsicum, red paprika',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0, 
                price:'395',
            },
            {
                id:2,
                img:'https://images.dominos.co.in/new_margherita_2502.jpg',
                itemName:'Margherita',
                itemDesc:'Classic delight with 100% real mozzarella cheese',
                isVeg:'https://pizzaonline.dominos.co.in/static/assets/icons/veg.svg',
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'395',
            },
            {
                id:3,
                img:'https://images.dominos.co.in/new_mexican_green_wave.jpg',
                itemName:'Mexican Green Wave',
                itemDesc:'Mexican herbs sprinkled on onion, capsicum, tomato & jalapeno',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'395',
            },
            {
                id:4,
                img:'https://images.dominos.co.in/new_cheese_n_corn.jpg',
                itemName:'Cheese n Corn',
                itemDesc:'A delectable combination of sweet & juicy golden corn',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'305',
            }
        ],
    },
    {
        id:3,
        name:'NonVeg pizza',
        items:
        [
            {
                id:1,
                img:'https://images.dominos.co.in/CreamyTomatoPPNV_N.jpg',
                itemName:'Creamy Tomato Pasta Pizza - Non Veg',
                itemDesc:'Loaded with a delicious creamy tomato pasta topping, BBQ pepper chicken, green capsicum, crunchy red and yellow bell peppers',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'395',
            },
            {
                id:2,
                img:'https://images.dominos.co.in/new_non_veg_supreme.jpg',
                itemName:'Non Veg Supreme',
                itemDesc:'Supreme combination of black olives, onion, capsicum, grilled mushroom, pepper barbecue chicken, peri-peri chicken & grilled chicken rashers',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'570',
            },
            {
                id:3,
                img:'https://images.dominos.co.in/new_chicken_fiesta.jpg',
                itemName:'Chicken Fiesta',
                itemDesc:'Grilled chicken rashers, peri-peri chicken, onion & capsicum, a complete fiesta',
                isVeg:true,
                size:['small','medium','large'],
                isFavourite:false,
                qty:0,
                price:'450',
            }
        ],
        
    }
]